[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
extra_scripts =
    pre:scripts/wav_to_c.py
lib_deps =
    jesdev-io/jescore@^2.2.3

build_flags =
    -DCORE_DEBUG_LEVEL=0

; Override these when selecting another WAV file:
; audio_wav = audio/test_sine.wav
; audio_header = src/audio_data.h
